### ISSUE TITLE
Autoloader error

### ISSUE THREAD

**Issue by chedaroo** [e-sites/magento-advanced-html-editor#3]
I was getting an exception saying the following file couldn't be found by autoloder:
"Esites/Editor/Model/System/Config/Source/Indentunit/Values.php"

I resolved it by removing some capitalisation and changing directory structure from this:
"Esites/Editor/Model/System/Config/Source/IndentUnit/Values.php"

to this: 
"Esites/Editor/Model/System/Config/Source/Indentunit/Values.php"

I'm sure you'd have found it but thought I'd let you know, good work on the module BTW.

**Comment by boye** [comment]
Indeed, we ran into it as well, but still thanks for reporting it! I will try to land a patch today.
