### ISSUE TITLE
Is it possible to make this the default text editor for products

### ISSUE THREAD

**Issue by lfolco** [e-sites/magento-advanced-html-editor#4]
Rather than having to click 'Wysiwyg Editor' and then click the source button? Similar to how it works with the transactional emails.

**Comment by boye** [comment]
Good one, i'll take that in consideration for the next release.

**Comment by boye** [comment]
Update: as of version 0.5.0 it will be possible to turn _any_ `<textarea>` in the admin panel into an advanced (stand-alone) editor. It's simply a matter of passing a CSS selector via the corresponding configuration option.

![screen shot 2015-10-23 at 08 22 04](https://cloud.githubusercontent.com/assets/135641/10692420/6ea421f2-795f-11e5-8e45-f4f1659b4105.png)

**Comment by lfolco** [comment]
awesome!

**Comment by chedaroo** [comment]
This is awesome!

**Comment by boye** [comment]
@chedaroo great to hear! :)
