### ISSUE TITLE
each time on save, i lose the code

### ISSUE THREAD

**Issue by ali-hellani** [e-sites/magento-advanced-html-editor#7]
Hi,

each time i save the block i lose the code that is between the div **(social-icons)**, i've tried many different ways, i found that if i put anything inside this div even `(&nbsp;)`, it works !

```
<div class="social-icons">
    <a href="http://facebook.com/transvelo" class='active'><i class="icon fa fa-facebook"></i></a>
    <a href="#"><i class="icon fa fa-twitter"></i></a>
    <a href="#"><i class="icon fa fa-linkedin"></i></a>
    <a href="#"><i class="icon fa fa-rss"></i></a>
    <a href="#"><i class="icon fa fa-pinterest"></i></a>
</div>
```

**Comment by boye** [comment]
Hi @ali-hellani,

It seems that the issue you mention is most likely related to the WYSIWYG editor itself, rather than the Advanced Editor extension. The extension doesn't process the user input in any way upon saving.

So my guess is that this is a TinyMCE setting...that it somehow removes empty HTML nodes.

Cheers,
Boye

**Comment by ali-hellani** [comment]
Thanks for your reply.

before i install the extension, i faced the same issue and you are right, it is **TinyMCE** thing, but I've solved that by adding `extended_valid_elements : '+a[*]'` to the setup file and it worked. So i think it is the same problem, but how i can overcome that using the extension, IDK :)

**Comment by boye** [comment]
Well, the extension doesn't force (or remove) any TinyMCE settings....so are you sure the `extended_valid_elements` option is working properly when the extension is disabled?

If so, I will test it myself in my local environment to see if there might be any conflicts.
