### ISSUE TITLE
esites logo causes insecure https lock / window not resizeable

### ISSUE THREAD

**Issue by gjvdheuvel** [e-sites/magento-advanced-html-editor#8]
Hi guys,

I love your plugin and it really helps a lot whiel editing and detecting possible html errors but two things bother me:

1) the Esites logo in the System -> Config causes loss of the secure green https lock in the backend. It points to an image on your servers. Please just include that image in the package, make it local and then on https shops, it will point to the https version of the logo. Now I just disable it in the system.xml to work around this.

2) The edit window is not resizeable. I do my editing on a 21:9 monitor and I would love to have a wider edit window. Can you please allow resizing of the edit window ?

Thanks,

Gert-Jan van den Heuvel

**Comment by boye** [comment]
Hi @gjvdheuvel,

Thanks for your feedback! I will try to land a fix for both issues this week.

Cheers

**Comment by boye** [comment]
Both issues are fixed as of version 0.6.2. I will publish the release to Magento Connect / Marketplace later today.

**Comment by boye** [comment]
@gjvdheuvel by the way...feel free to leave a review on Magento Connect or Magento Marketplace if you have some spare time ;)

**Comment by gjvdheuvel** [comment]
Zal ik zeker doen ;)

Op 11 apr. 2017 14:24 schreef "Boye" <notifications@github.com<mailto:notifications@github.com>>:

@gjvdheuvel<https://github.com/gjvdheuvel> by the way...feel free to leave a review on Magento Connect or Magento Marketplace if you have some spare time ;)
